name: Build and deploy Python project to Azure Function App - serverlessdevopsfunc
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Add Debug Steps Here
      - name: Debug Environment
        run: |
          echo "Current working directory:"
          pwd
          echo "\nDirectory contents:"
          ls -la
          echo "\nPython version:"
          python --version
          echo "\nPip version:"
          pip --version
          echo "\nFull directory tree:"
          tree -a

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Add more debug steps before installation
      - name: Pre-installation check
        run: |
          echo "Checking for requirements.txt:"
          test -f requirements.txt && echo "Found requirements.txt" || echo "requirements.txt NOT FOUND"
          echo "\nContent of requirements.txt:"
          cat requirements.txt || echo "Could not read requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      [Rest of your existing workflow...]