name: Build and deploy Python project to Azure Function App - serverlessdevopsfunc
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debug File Location
        run: |
          echo "Current directory:"
          pwd
          echo "\nList root directory:"
          ls -la
          echo "\nFind requirements.txt:"
          find . -name requirements.txt
          echo "\nContent of requirements.txt (if found):"
          cat requirements.txt || echo "File not found"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Verify Python environment
        run: |
          which python
          python --version
          pip --version
          echo "PWD: $(pwd)"
          echo "PYTHONPATH: $PYTHONPATH"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found in $(pwd)"
            echo "Directory contents:"
            ls -la
          fi