name: Build and deploy Python project to Azure Function App - serverlessdevopsfunc
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Step 3: Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Create and activate virtual environment
      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Verify host.json before packaging
      - name: Verify host.json
        run: |
          echo "Checking host.json content:"
          cat host.json
          echo "Validating JSON syntax:"
          python -m json.tool < host.json

      # Step 6: Zip artifact for deployment
      - name: Zip artifact for deployment
        run: |
          echo "Current directory contents before zip:"
          ls -la
          echo "Creating zip file..."
          zip release.zip ./* -r
          echo "Verifying zip contents:"
          unzip -l release.zip | grep host.json
          echo "Zip file size:"
          ls -lh release.zip

      # Step 7: Deploy to Azure Function App
      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: serverlessdevopsfunc
          package: './release.zip'

      # Step 8: Verify Deployment
      - name: Verify Deployment
        run: |
          echo "Checking deployment status"
          echo "Function App name: serverlessdevopsfunc"
